### ISSUE TITLE
Why do we have to use an OAuth2 service if we consider to host it in the company network ?

### ISSUE THREAD

**Issue by menardorama** [alerta/angular-alerta-webui#16]
Hi,

I'm trying to integrate your product in my company to aggregate all of our zabbix servers.

My concern here is it seems to be mandatory to have an OAuth with google or github to display the alerts.

But I don't want to expose it outside my company.... 

Is there a work arround for that ?

By the way I tried to setup even google or twitter auth without success, I always have a json popup and never get logged in.

It seems that I need a callback url (saw it on the docker alerta page), but I don't know what to put.

I tried to put the same as the homepage url but it fail.

Have you got any idea ?

And last to be really clear, I've also setup the alertad oauth part and alerts are being pushed successfully by zabbix in my mongodb db.

Thanks for your help

**Comment by satterly** [comment]
There is comprehensive documentation on setting up authentication on the docs website ... http://docs.alerta.io/en/latest/authentication.html If you still can't get OAuth2 working I'd like to know as I've spent a lot of time trying to make a potentially complex aspect of the config as straight-forward as possible.

Note though, that it is not mandatory to use authentication at all. The default out-of-the-box configuration does not require any authentication ... https://github.com/guardian/alerta/blob/master/alerta/settings.py#L23 However, you won't be able to "watch" alerts in the console because alerta won't know who's logged.

BTW, thanks for letting me know about the Docker documentation -- it seems to be out-of-date. I'll fix it.

**Comment by satterly** [comment]
Fixed in #17
