### ISSUE TITLE
Last commit is breaking Google Oauth

### ISSUE THREAD

**Issue by tjongerius** [alerta/angular-alerta-webui#199]
**Issue Summary**
https://github.com/alerta/angular-alerta-webui/commit/c23e30542e4865251f5822a8a06a336bb8ff8c58 is breaking Google OAuth.

No more clickable button when applying last commit.

**Comment by satterly** [comment]
You didn't fill in the issue template. Now i have to ask lots of questions :(

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....' or Run '...'
3. Scroll down to '....'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
