### ISSUE TITLE
Webui does not show alert

### ISSUE THREAD

**Issue by colomboipl** [alerta/angular-alerta-webui#61]
Hello , 

I have the latest alerta installed and working on localhost:10000

I have installed the alerta-angular_3 and copyed the app folder to my server. The alerta-server and webui are on the same server

When I create an alert its show in the api but not on the webui page.

The CORS is OK and i dont have any error on javascript console.

What is the problem?

Best Regards,
Arnaldo

**Comment by colomboipl** [comment]
ok it's normal now. just can run from apache server.

**Comment by richerve** [comment]
Hi, what does that mean? The only way to running now is using a WSGI server?

For me it's not working even with SimpleHTTPServer but I can request the api, with curl for example, and I'm getting the alerts.

Is there any release schedule on the project? I'm asking because following master seems to be error prone.

Thank you,
Ricardo

**Comment by satterly** [comment]
@richerve no, don't run the web UI as a wsgi app. It is just a set of files that can be served as static assets from anywhere -- as long as you set the CORS setting correctly on the server. If you have a specific problem create a new GitHub issue with as much information as you can provide and I'll take a look.

**Comment by richerve** [comment]
Sorry I mix the server config with the ui. I will open a new issue with the information if necessary
