### ISSUE TITLE
Create/update users

### ISSUE THREAD

**Issue by bcanyelles** [alerta/angular-alerta-webui#95]
Hi, 

I have a question about how can create users. I've seen that `apps/partials/users.html` has the form block commented and I'm wondering if it should be uncommented or it was done by purpose.

On the other hand, could be a good feature add a role field in the same form.
¿What is your opinion about update users?¿Do you think that it's a great solution use the same form to update password and role for the specified user? 
This feature only affects to `@app.route('/user', methods=['OPTIONS', 'POST'])` view, where it should looking for by username or login fields and cal to `update_user` instead of` create_user`.

Thanks.

**Comment by satterly** [comment]
Hi @bcanyelles, the (commented-out) user create form should have been removed a long time and it is now (see b3b074edcd02b93088da0d204e3756e0c87033ad). It's redundant because there's no reason for an admin to create a user when the user could do it themselves and set a password at the same time.

You can currently change the role for a user in the users list. I would need to think about how this view could be extended to allow an admin to set a password. It would be better to allow users to reset their own passwords but this would only work if email verification was enabled.

I'll have a think and get back to you. Let me know if you have any further thoughts on this. Thanks.

**Comment by satterly** [comment]
It's now possible to use the the User web page to change the user role...

<img width="1071" alt="screen shot 2017-11-14 at 22 43 11" src="https://user-images.githubusercontent.com/615057/32809059-5775f192-c98d-11e7-8446-0774479df2af.png">

Changing the user password is not currently supported in the web UI. It is supported using the `alerta` CLI though...

```
$  alerta users
STATUS    LAST UPDATED         USER    ROLES    VERIFIED    TEXT    LAST LOGIN           ID                                    CREATED              EMAIL
--------  -------------------  ------  -------  ----------  ------  -------------------  ------------------------------------  -------------------  ---------------
active    2017/11/14 22:37:49  admin   admin    no          admin   2017/11/14 22:45:01  86ca98af-8406-4ca6-901b-f5ff10495823  2017/11/14 22:37:49  admin@alerta.io

$ alerta user -i 86ca98af-8406-4ca6-901b-f5ff10495823 --password foo
```
I'll add the ability to change the password to the web UI to the back log.
